### ISSUE TITLE
Enable wildcard with a * symbol in coding systems where '.' is irrelevant

### ISSUE THREAD

**Issue by RosaMGini** [ARS-toscana/CreateConceptSetDatasets#14]
If the concept set contains a string with a *, a string matching should be enabled that considers * as a wildcard.

Proposal: 

in the conceptsets:
1) replace '.' with ''
2) replace '*' with '.'
3) enable comparison with regex

**Comment by DavideMessinaARS** [comment]
Done in https://github.com/ARS-toscana/CreateConceptSetDatasets/commit/ef23ffb2f3af1fe4ced052d419b982e62815d091

Tested on the example. (Which I've modified with a wildcard in it).

Added to v27 as CreateConceptSetDatasets_v14

**Comment by RosaMGini** [comment]
wow. that was quick.
