### ISSUE TITLE
Execution time improvement

### ISSUE THREAD

**Issue by carlosvergara** [ARS-toscana/CreateConceptSetDatasets#3]
Hi,

After reviewing the function I have seen that there is a bottleneck when detecting the codes associated with each set: for each code in each set that you want to detect, a filter is run on the database to select the appropriate records (eg, on line 144: `used_df[(str_detect(gsub("\. ", "", get(col)), gsub("\.", "", paste0("^", single_cod))))]`), which is computationally expensive given the size of the original table.

To increase the execution speed it would be enough to extract all common computation from the for loops (by creating a common variable that can be used several times):

```
for (col in codvar[[concept_set_domains[[concept]]]][[df2]]) {
  used_df[, paste0(col, "_tmp") := gsub("\\.", "", get(col))] # Creation of the new variable: codes without a dot
  for (type_cod in names(concept_set_codes[[concept]])) {
    codes_rev <- concept_set_codes[[concept]][[type_cod]]
    if ("ALL_CODES" %in% codes_rev) {
      print("allcodes")
      used_df[, Filter := 1]
      used_df[, paste0("Col_", concept) := codvar[[dom]][[df2]][1]]
    } else {
      if ((!missing(vocabulary))) {
        if (df2 %in% dataset[[dom]]){
          if (dom %in% names(vocabulary)) {
            used_df[
              (
                str_detect(
                  get(paste0(col, "_tmp")),
                  gsub("\\.", "", paste(paste0("^", codes_rev), collapse = "|")) # Using our new variable, we search for all codes at once
                )
              ) & get(vocabulary[[dom]][[df2]]) == type_cod,
              c("Filter", paste0("Col_", concept)) := list(1, col)
            ]
          }  # [cont...]
```

In this way the computation time and memory usage is greatly reduced.

Thanks for your work.

Best regards! :)

**Comment by RosaMGini** [comment]
hi carlos, 

this is a great advice, thank you so much! and thanks for testing. we will definitely incorporate it in our next release :)

cheers, rosa

**Comment by OlgaPaoletti** [comment]
Hi Carlos,

I implemented you suggestion and the time of execution was reduced of about 60%.

It was very useful. 

Thank you,

Olga Paoletti
