### ISSUE TITLE
Preliminary selection of coding systems that are included in the analysis

### ISSUE THREAD

**Issue by RosaMGini** [ARS-toscana/CreateConceptSetDatasets#7]
When the function browses a file it looks for all codes in all coding systems included in the list -concept_set_codes-

Would it be possible to create, first, the subset of the coding systems that are actually included in the file, and just looks for the corresponding codes?

**Comment by OlgaPaoletti** [comment]
Resolved in: https://github.com/ARS-toscana/CreateConceptSetDatasets/pull/12
