### ISSUE TITLE
Bug in reading EAVattributes

### ISSUE THREAD

**Issue by RosaMGini** [ARS-toscana/CreateConceptSetDatasets#8]
There is an error triggered by an EAVattribute set to a empty list, see MWE here

https://www.dropbox.com/home/ACCESS_project/23.%20BGR%20script/troubleshooting/SIDIAP/210208

**Comment by OlgaPaoletti** [comment]
Solved with commit c57a33d8d26ddd4c24281d7e2ef01761d0f59073
